[features]
seeds = false

[programs.devnet]
solana_project = "GNxTdcqwJMPmbNGx9KN5EhtL8PniKUTXA9zuU197uwmg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./post_audit.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
