[features]
seeds = false

[programs.devnet]
solana_project = "3hyoKShH2xk4hB5gXp6J3dyMEtxdzpj1SSScP1LsRzN8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./post_audit.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
