[features]
seeds = false

[programs.mainnet]
solana_project = "2w1QMXDTsWCmpdPHfjrL9SbkKeh3K37WMqJQUfnXHzRh"

[programs.devnet]
solana_project = "3qAAmNxTHxeL6pKDC6nb2PmoCE6hgZM2QXtS88gBm3yL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rosh/.config/solana/id.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
